trigger:

- main

pool:
  vmImage: ubuntu-latest

variables:
  myImages: |
    naresh74/newaravaimage:latest
    naresh74/newaravaimage:latest
    naresh74/newaravaimage:latest
    naresh74/newaravaimage:latest

stages:
- stage: STAGE_PULL_DOCKER_IMAGE
  jobs:
  - job: PullImages
    steps:
    - script: echo Steps for pipeline
      displayName: 'pipeline for pulling the image'


    - task: Docker@2
      displayName: login to docker
      inputs:
        containerRegistry: 'dockerconnection'
        command: 'login'

    - script: |
          images=(
                    "naresh74/newaravaimage:latest"
                    "naresh74/newaravaimage:latest"
                    "naresh74/newaravaimage:latest"
                    "naresh74/newaravaimage:latest"
                  )
    - task: CmdLine@2
      displayName: 'docker pulling the image'
      inputs:
        script: |
          IFS=$'\n' read -d '' -r -a images <<< "$(echo "$myImages")"
          for image in "${images[@]}"; 
          do
            #echo NameDockerImage:"$image"
            echo $image
            docker pull $image
          done

    - script: |
        for i in "${!images[@]}"; do
         image[i]=$(echo "${image[i]}" | sed 's/naresh74/khazeuscazurecrio/g')
         docker push "${image[@]}"
        done
        echo "${image[@]}"
      displayName: 


    - task: CmdLine@2
      displayName: 'Replace Container Registry'
      inputs:
        script: |
           for i in "${!images[@]}"; do
            images[i]=$(echo "${images[i]}" | sed 's/naresh74/khazeuscazurecrio/g')
            echo "${images[@]}"
            docker push "${images[@]}"
           done