trigger:
  - main
stages:
- stage: __default
  jobs:
  - job: Job
    steps:
    - task: CmdLine@2
      displayName: 'Echo Steps'
      inputs:
        script: echo "Step - Docker Login, Docker Image Pull"
#    - task: Docker@2
 #     displayName: 'Login to GCR Container Registry'
  #    inputs:
   #     command: login
    #    containerRegistry: 'Collibra_DQ_OWL_Images_GCR'
    - task: CmdLine@2
      inputs:
        script: |
          images=(
                    "gcr.io/owl-hadoop-cdh/owl-web:2023.05.1-ABDGCSHILM-258"
                    "gcr.io/owl-hadoop-cdh/owl-agent:2023.05.1-ABDGCSHILM-258"
                    "gcr.io/owl-hadoop-cdh/owl-livy:3.2.2-2023.05.1-ABDGCSHILM-258"
                    "gcr.io/owl-hadoop-cdh/spark:3.2.2-2023.05.1-ABDGCSHILM-258"
                  )
                   for image in "${images[@]}"; do
                     echo "Pulling $image"
                   done
                   for i in "${!images[@]}"; do
                      image[i]=$(echo "${image[i]}" | sed 's/gcr.io/khazeuscazurecrio/g')
                      echo "image tag $image"
                   done

      displayName: checking


    - script: |
          for image in "${images[@]}"; do
           echo "Pulling $image"
          done
      displayName: checking the image